#poisson m.
#The Poisson model is used for modeling count data where the outcome variable
#is a count (i.e., 0, 1, 2, 3, ...). The key assumption of the Poisson model
#is that the mean and variance of the count variable are equal.

# Load necessary library
library(MASS)

# Example data
data <- data.frame(
  count = c(18, 17, 15, 20, 10, 20, 25, 13, 12), #y
  predictor = c(1, 2, 3, 4, 5, 6, 7, 8, 9)      #x
)

# Fit Poisson regression model
poisson_model <- glm(count ~ predictor, family = poisson, data = data)

# Summary of the model
summary(poisson_model)


#negative binomail model
#The Negative Binomial (NB) model is an extension of the Poisson model that
#relaxes the assumption of equidispersion (i.e., the mean and variance are equal). 
#The NB model is used when the data exhibit overdispersion 
#(i.e., the variance is greater than the mean).

## Load necessary library
library(MASS)

# Example data
data <- data.frame(
  count = c(18, 17, 15, 20, 10, 20, 25, 13, 12),
  predictor = c(1, 2, 3, 4, 5, 6, 7, 8, 9)
)

# Fit Negative Binomial regression model
nb_model <- glm.nb(count ~ predictor, data = data)

# Summary of the model
summary(nb_model)

#zip
#Zero-inflated models are used for count data with an excess of zero counts. 
#These models assume that the data are generated by two processes: one that produces only zeros
#and another that generates counts from a standard distribution (Poisson or Negative Binomial).
#Zero-inflated models combine these two processes to better handle overdispersion and excess zeros.

# Load necessary library
install.packages("pscl")
library(pscl)
# Example data
data <- data.frame(
  count = c(0, 0, 1, 2, 3, 0, 4, 5, 0, 6),
  predictor = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
)
# Fit Zero-Inflated Poisson model
zip_model <- zeroinfl(count ~ predictor | predictor, data = data, dist = "poisson")
# Summary of the model
summary(zip_model)

# Example data
data <- data.frame(
  count = c(0, 0, 1, 2, 3, 0, 4, 5, 0, 6),
  predictor = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
)
# Fit Zero-Inflated Negative Binomial model
zinb_model <- zeroinfl(count ~ predictor | predictor, data = data, dist = "negbin")
summary(zinb_model)




#Quantile regression is a statistical technique used to model the relationship 
#between predictors and the conditional quantiles of the response variable. 
#Unlike ordinary least squares (OLS) regression, which models the conditional mean
#of the response variable, quantile regression allows us to examine how the predictors 
#affect different quantiles of the response distribution. This makes quantile regression
#useful for studying the entire conditional distribution of the response variable and 
#for assessing the effects of predictors across different parts of the distribution.

# Load necessary library
install.packages("quantreg")
library(quantreg)

# Example data
data <- data.frame(
  x = c(1, 2, 3, 4, 5),
  y = c(2, 3, 5, 7, 10)
)

# Fit quantile regression model for the median (tau = 0.5)
quantreg_model <- rq(y ~ x, data = data, tau = 0.5)

# Summary of the model
summary(quantreg_model)

# Predictions for the 0.25 and 0.75 quantiles
predictions <- predict(quantreg_model, newdata = data.frame(x = c(2.5)), interval = "confidence", level = 0.95)




#model selection criteria
# Load necessary libraries
library(MASS)
install.packages("leaps")
library(leaps)

# Example data
data <- data.frame(
  y = c(2, 3, 5, 7, 10),
  x1 = c(1, 2, 3, 4, 5),
  x2 = c(3, 4, 2, 5, 1)
)

# Fit multiple linear regression models with different subsets of predictors
model_full <- lm(y ~ x1 + x2, data = data)
model_x1 <- lm(y ~ x1, data = data)
model_x2 <- lm(y ~ x2, data = data)

# Calculate AIC for each model
aic_full <- AIC(model_full)
aic_x1 <- AIC(model_x1)
aic_x2 <- AIC(model_x2)

# Compare AIC values
aic_values <- c("Full Model" = aic_full, "Model with x1" = aic_x1, "Model with x2" = aic_x2)
print(aic_values)

# Select the model with the lowest AIC
best_model <- min(aic_values, na.rm = TRUE)





